baseURL = "https://manuflores.github.io/topological-cell-observatory"
languageCode = "en-us"
title = "topological cell observatory"
theme = "brewm"

## Enable Git information for pages, (e.g. lastMod date information)
enableGitInfo = true
## Convert all URLs to absolute URLs
canonifyURLs = true
## Default language for content
defaultContentLanguage = 'en'
## Put default language in subdirectory
defaultContentLanguageInSubdir = true
## Show placeholder for missing translations
enableMissingTranslationPlaceholders = truez
## Use sections for main menu
# sectionPagesMenu = 'main'
## Files to ignore when building site
ignoreFiles = [ '\.redacted', '\.old','\.bak', '\.tmp', '\.swp', '\.DS_Store']
## Errors to ignore in logs
# ignoreLogs = ['err-youtube-remote']
## Copyright notice
copyright = 'Copyright 2025 (c) Foxxi'

## Front matter field configurations
[frontmatter]
    ## Publication date fields
    date = [':default']
    ## Expiry date fields
    expiryDate = ['expiryDate', 'unpublishdate', ':default']
    ## Last modified date fields
    lastmod = ['lastmod', ':default'] ## ":fileModTime"

## Markup configuration
[markup]

    ## Table of contents settings
    [markup.tableOfContents]
        ## Minimum heading level to include
        startLevel = 2
        ## Maximum heading level to include
        endLevel = 3
        ## Use ordered list for TOC
        ordered = false

    ## Code highlighting settings
    [markup.highlight]
        ## Enable code fence highlighting
        codeFences = true
        ## Lines to highlight
        hl_Lines = ""
        ## Starting line number
        lineNoStart = 1
        ## Show line numbers
        lineNos = false
        ## Put line numbers in table
        lineNumbersInTable = true
        ## Use classes for styling
        noClasses = false
        ## Width of tab character
        tabWidth = 4

    ## Goldmark markdown processor settings
    [markup.goldmark]
        [markup.goldmark.renderer]
            ## Allow HTML in markdown
            unsafe = true

## Sitemap configuration
[sitemap]
    ## Change frequency setting (will affect posts listings layout): 'always', 'hourly', 'daily', 'weekly', 'monthly', 'yearly', 'never'
    # changeFreq = 'monthly'
    ## Disable sitemap generation
    # disable = false
    ## Output filename
    # filename = 'sitemap.xml'
    ## Priority setting
    # priority = -1

## RSS configuration
[services.rss]
    ## Limit RSS item
    limit = -1

## Taxonomy configuration
[taxonomies]
    ## Category taxonomy
    category = "categories"
    ## Tag taxonomy
    tag = "tags"
    ## Series taxonomy
    series = "series"

## Site parameters
[params]
    ## Site title
    title = "topological cell observatory"
    ## Site description
    description = "topology"
    ## Copyright notice
    copyright = "Copyright 2025 (c) Thomson Lab"
    ## Enable extended metadata (social cards)
    extMeta = true
    ## Enable coffee metric
    coffeeStat = true

    ## Author information
    [params.author]
        ## site author's name
        name = 'Manu Flores'
        ## Author's email (will be used for RSS feed)
        email = 'manuflores@caltech.edu'
        ## Co-authors information (optional)
        coauthor = [
            {name = "Binglun Shao", bio = "Grad student in Thomson Lab"}
        ]

    ## Comments configuration
    [params.comments]
        ## Disable comments (disable fediverse comments)
        disabled = true
        ## Comment platform selection, currently only 'fediverse' is supported, further options to be determined
        # platform = 'fediverse'

    ## Fediverse integration settings
    [params.fediverse]
        ## Fediverse instance URL
        instance = 'example.com'
        ## Fediverse username
        username = 'username'

    ## Logo configuration
    [params.logo]
        ## Light mode logo mark
        # logoMark = 'https://example.com/logoMark.svg'
        ## Dark mode logo mark
        # logoMarkDark = 'https://example.com/logoMarkDark.svg'
        ## Enable logo type
        logoType = true

    ## Feed display settings
    [params.feed]
        ## Enable flowlines
        flowlines = true
        ## Limit number of flowlines
        flowlinesLimit = 21
    
    ## Home page display settings
    [params.home]
        ## Enable slide carousel
        disableSlide = false
        ## Enable taxonomy listing carousel
        disableListing = false

    ## Post display settings
    [params.posts]
        ## Enable text justification
        justifying = false
        ## Disable paragraph indentation
        noIndent = false
        ## Show colophon section (including QR code)
        colophon = true
        ## disable redaction history
        disableHistory = false
        ## SHow related content
        related = true
        ## Show share buttons
        share = true

    ## Search configuration
    [params.search]
        ## Enable search functionality, use duckduckgo (no javascript)
        enable = true
        ## Use pagefind search when javascript enabled, currently only 'pagefind' is supported, further options to be determined
        pagefind  = true

    ## Typography settings
    [params.typeface]
        ## Use web safe fonts (will overide font selection below)
        webSafe = false
        ## Serif font selection
        roman = 'crimson'
        ## Sans-serif font selection
        sans = 'inter'
        ## use typeface stored in local server (pleaase download font's uri first)
        localHost = false

    ## Extended Metadata and  Social card configuration
    [params.socialCard]
        ## Enable twitter and opengraph social cards (same .params.extMeta setting)
        enable = true
        ## Default social card image
        # image = "img/social-share.jpg" ## recommended resolution: 1200 x 630px

        ## Enable Twitter cards
        # twitter = true
        ## Twitter creator handle
        # twitterCreator = "@username"
        ## Twitter site handle
        # twitterSite = "@username"

        ## Enable OpenGraph
        # opengraph = true
        ## Facebook App ID
        # facebookAppID = "123456789"
        ## Facebook Admin ID
        # facebookAdmin = "USER_ID"

        ## Schema.org (only meta, not fully supported)
        # schema = true
        ## JsonLD (cannot validate permalink)
        # jsonLD = true
