[en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-GB'
    languageDirection = 'ltr'
    languageName = 'English'
    [en.pagination]
        disableAliases = false
        pagerSize = 12
        path = 'page'
    [en.taxonomies]
        author = 'author'
        category = 'categories'
        series = 'series'
        tag = 'tags'

[es]
    contentDir = 'content/es'
    disabled = false
    languageCode = 'es-ES'
    languageName = 'Español'